### ISSUE TITLE
Not Compatible with no-title-bar plugin

### ISSUE THREAD

**Issue by imtiazwazir** [arcticicestudio/northem-light-atom-ui#11]
<img width="1440" alt="screen shot 2016-11-11 at 9 34 23 am" src="https://cloud.githubusercontent.com/assets/1964969/20204523/359edad8-a7f2-11e6-9e9a-ef66dc769f71.png">

**Comment by arcticicestudio** [comment]
I'll close this one since Atom now supports this package feature by default.
