### ISSUE TITLE
The selected file is unbolded

### ISSUE THREAD

**Issue by linjialiang** [arcticicestudio/northem-light-atom-ui#23]
> `Desired effect` : The currently selected file is bold

![default](https://user-images.githubusercontent.com/8848263/41133819-ad63cfc4-6afb-11e8-898a-fa82c685cc39.png)

---

> `at present`

![default](https://user-images.githubusercontent.com/8848263/41133895-1add4c06-6afc-11e8-8879-ac814f5de0c9.png)

**Comment by linjialiang** [comment]
@edwardloveall  @arcticicestudio  

> Can we deal with the above problems !

**Comment by arcticicestudio** [comment]
The first screenshot shows another UI theme ([Nucleus Dark][ndui]) while the second one shows the [Northem Light Atom][nlaui]. Both are two different UI themes developed by different maintainer.

You can add the following selector to your `~/.atom/styles.less` file (_Edit_ -> _Stylesheet…_) to use a bold font for the actually selected tree item:

```less
.tree-view .list-tree li:not(.list-nested-item).selected {
  font-weight: bold;
}
```

[ndui]: https://atom.io/themes/nucleus-dark-ui
[nlaui]: https://atom.io/themes/northem-light-atom-ui
