### ISSUE TITLE
No visually difference of the active tab

### ISSUE THREAD

**Issue by edwardloveall** [arcticicestudio/northem-light-atom-ui#6]
In #3 I gave the feedback that the current tab is hard to discern and @arcticicestudio agreed.

Possible solutions:

* Highlight the whole tab with a separate background color
* Add a line on the left/right/bottom edge of the tab

My preference would be for changing the background color like the theme currently does. That not only gives a feel of which tab is selected, but how wide each tab is. My eye can easily extrapolate the other tab widths because of this.

I actually really do enjoy the tab style that this theme currently has :)

**Comment by arcticicestudio** [comment]
I checked the code today and noticed that this is actually a bug.
I implemented styles for it, but it gets overriden by an selector that sets specific rules for an `MarkdownPreview` tab.

**Comment by arcticicestudio** [comment]
Now using `northem-light5` color for the current active tab which  seem to fit with most syntax themes:

<p align="center"><strong>Northem Light Atom Syntax</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/20155714/6448707c-a6cd-11e6-9396-fef3609521d4.png"/><br><strong>One Light</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/20155811/d6a4e704-a6cd-11e6-91e6-ba90b10e7e24.png"/><br><strong>Base16 Tomorrow Light</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/20155747/8cfbb650-a6cd-11e6-8c9b-92cfb3cd84d5.png"/></p>

Solves related issue #7.

**Comment by edwardloveall** [comment]
Yeah! I think this helps a lot. Thank you.
