### ISSUE TITLE
Can't tell if a file is saved

### ISSUE THREAD

**Issue by edwardloveall** [arcticicestudio/northem-light-atom-ui#7]
In #3, I had the problem of not being sure if a file was saved or not. I think your visual indicator works fine, but the problem was with nothing separating the tabs, it's difficult to understand which tab has the "unsaved circle". I.e. is the circle on the right side of tab A or left side of tab B:

```
|        Tab A        °        Tab B        |
```

This is related to #6

**Comment by arcticicestudio** [comment]
Closed by #6.
