### ISSUE TITLE
Option to reduce contrast of drop downs, buttons, and text fields

### ISSUE THREAD

**Issue by edwardloveall** [arcticicestudio/northem-light-atom-ui#8]
In #3 I had the feedback that the focus color on fields is too bright. @arcticicestudio responded:

>The input fields, drop-downs and button outlines are designed to be bright on purpose.
Nord Atom UI- and Syntax are not meant to be pure dark themes but try to give a "north blue" feel and the bright white colors can be compared to ❄️ snow.

This gets a little weird to talk about because the theme in question was a dark one and this is a light theme. Anyway, the point I was trying to get across was that it felt out of place to have UI with such a low contrast have a small number of high contrast elements, especially when those elements didn't seem to have more importance than others.

You did offer a solution:

>Maybe this could be solved by adding a theme setting to disable bright theme components for a more dark feel?

That would be great, but even just letting people customize it with their custom stylesheet would be fine. This may just come down to personal preference, not a problem that has a defined solution.

**Comment by arcticicestudio** [comment]
I see your point about the contrast difference and I think it is indeed a personal preference, but I'll stay with the current design.
Users who like to change the color can use the Atom "hackable" way by using their custom stylesheet as you mentioned.
