### ISSUE TITLE
Fade content when panels are active

### ISSUE THREAD

**Issue by edwardloveall** [arcticicestudio/northem-light-atom-ui#9]
In #3, I mentioned that the panels don't fade the content at all. @arcticicestudio responded:

>Also thought about adding more shades for more depth, but I don't want to use it too much to not destroy the flat feel of theme (I don't really like the "Material" design).

Fair enough, and this may just be another preference issue and not a problem.

I do disagree with the depth issue though. I think the issue is focus by using contrast, not depth. Contrast the panels against the content and they're easier to focus on. Also, the panels all have a subtle shadow to them which is already giving depth. I'm not actually sure if a color shade would add more depth or not, but my gut says "no" or "not much".

**Comment by arcticicestudio** [comment]
Like #8 this is a personal preference and users may use their custom stylesheet to accomplish this effect.
